# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 17:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persongroup',
            name='name',
            field=models.CharField(db_index=True, max_length=128, validators=[django.core.validators.RegexValidator('^[a-z0-9]+$', '숫자/영소문자로만 입력해주세요.')]),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('group', 'name')]),
        ),
    ]
